server:
  port: 18082
spring:
  application:
    name: itheima-order #微服务架构中 应用名称必须配置
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-order?characterEncoding=UTF8&&serverTimezone=Asia/Shanghai
    username: root
    password: root