server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
      discovery:
        cluster-name: SZ
        #环境隔离 配置当前是开发环境 test
        namespace: 3ce572ca-30ff-46df-8429-bedaafe49e0a
    gateway:
      routes: # 网关路由配置
        - id: user-service # 路由id，自定义，只要唯一即可
          # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
          uri: lb://itheima-user # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/** # 这个是按照路径匹配，只要以/user/开头就符合要求
            #在什么时间之前访问可以的
            - Before=2025-01-20T17:42:47.789-07:00[America/Denver]
          #路由过滤器工厂 在请求头中添加一个参数 请求头名称 name 请求头值 xiaohong
          filters:
            - AddRequestHeader=name,xiaoheiheihei
      #defaultFilters针对所有路由生效  filters：针对某个路由生效
      default-filters:
        - AddRequestHeader=name,xiaobaibaibai
#显示错误：[2d243475-4] There was an unexpected error (type=Internal Server Error, status=500).
        #- id: order-service # 路由id，自定义，只要唯一即可
          # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
          #uri: lb://itheima-order # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          #predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            #- Path=/order/** # 这个是按照路径匹配，只要以/user/开头就符合要求
